import type { DeploymentRecord } from './devops.types';

class DeploymentService {
  private deployments: DeploymentRecord[] = [];
  getDeployments(): DeploymentRecord[] { return [...this.deployments].sort((a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime()); }
  getLatestDeployment(): DeploymentRecord | null { return this.deployments.length > 0 ? this.getDeployments()[0] ?? null : null; }
  createDeployment(version: string, environment: 'development' | 'staging' | 'production', commitHash: string, deployedBy: string): DeploymentRecord { const record: DeploymentRecord = { id: `dep-${Date.now()}`, version, environment, status: 'building', deployedBy, startedAt: new Date().toISOString(), completedAt: null, commitHash, message: 'Deployment started' }; this.deployments.push(record); return record; }
  updateDeploymentStatus(id: string, status: DeploymentRecord['status'], message: string): void { const deployment = this.deployments.find((d) => d.id === id); if (deployment) { deployment.status = status; deployment.message = message; if (status === 'success' || status === 'failed' || status === 'rolled_back') { deployment.completedAt = new Date().toISOString(); } } }
  getDeploymentChecklist(): { id: string; description: string; required: boolean }[] { return [ { id: 'env-check', description: 'Environment variables validated', required: true }, { id: 'build-pass', description: 'Production build passes without errors', required: true }, { id: 'typecheck-pass', description: 'TypeScript type checking passes', required: true }, { id: 'db-migrations', description: 'All database migrations applied', required: true }, { id: 'rls-policies', description: 'Row Level Security policies verified', required: true }, { id: 'storage-buckets', description: 'Storage buckets configured', required: true }, { id: 'ssl-cert', description: 'SSL certificate configured', required: true }, { id: 'domain-config', description: 'Custom domain configured', required: false }, { id: 'cdn-setup', description: 'CDN configured for static assets', required: false }, { id: 'analytics-setup', description: 'Analytics tracking configured', required: false }, { id: 'backup-strategy', description: 'Backup strategy documented', required: true }, { id: 'health-checks', description: 'Health check endpoints verified', required: true }, { id: 'rollback-plan', description: 'Rollback plan documented', required: true } ]; }
  getRollbackSteps(): string[] { return [ '1. Identify the last known good deployment version', '2. Stop the current deployment process if still running', '3. Revert to the previous stable build artifact', '4. Run database migration rollback if schema changes were applied', '5. Clear CDN cache to ensure fresh assets are served', '6. Verify application health with health check endpoints', '7. Monitor error rates and user reports for 30 minutes', '8. Document the incident and root cause analysis' ]; }
}

export const deploymentService = new DeploymentService();
