import type { ReleaseInfo, ChangelogEntry } from './devops.types';

class ReleaseService {
  private releases: ReleaseInfo[] = [];
  _getReleases(): ReleaseInfo[] { return this.releases; }
  getCurrentVersion(): string { return import.meta.env.VITE_APP_VERSION ?? '6.2.0'; }
  getBuildNumber(): string { return import.meta.env.VITE_BUILD_NUMBER ?? '1'; }
  getGitHash(): string { return import.meta.env.VITE_GIT_HASH ?? 'unknown'; }
  getBuildDate(): string { return new Date().toISOString(); }
  getReleaseInfo(): ReleaseInfo { return { version: this.getCurrentVersion(), buildNumber: this.getBuildNumber(), gitHash: this.getGitHash(), buildDate: this.getBuildDate(), environment: import.meta.env.PROD ? 'production' : 'development', changelog: this.getChangelog() }; }
  getChangelog(): ChangelogEntry[] { return [ { version: '6.2.0', date: '2026-08-04', type: 'minor', changes: [ { type: 'added', description: 'Phase 6B: Enterprise SEO & Marketing Optimization' }, { type: 'added', description: 'Blog system with categories, tags, and SEO metadata' }, { type: 'added', description: 'Landing pages for NORCET, AIIMS, ESIC, DSSSB, CHO, RRB Nursing Officer' }, { type: 'added', description: 'Lead capture forms with UTM tracking' }, { type: 'added', description: 'Newsletter subscription system' }, { type: 'added', description: 'JSON-LD structured data (9 schema types)' }, { type: 'added', description: 'Dynamic sitemap generation and robots.txt' }, { type: 'added', description: 'Social sharing across 5 platforms' } ] }, { version: '6.1.0', date: '2026-08-04', type: 'minor', changes: [ { type: 'added', description: 'Phase 6A: Security hardening and audit logging' }, { type: 'added', description: 'Session security with device tracking' }, { type: 'added', description: 'Permission management system' } ] }, { version: '6.0.0', date: '2026-08-03', type: 'major', changes: [ { type: 'added', description: 'Phase 5: Payments, storage, video streaming, notifications, live classes, analytics' }, { type: 'added', description: 'Phase 2: Core LMS tables, content management, enrollment' } ] } ]; }
  getReleaseChecklist(): { id: string; description: string; required: boolean }[] { return [ { id: 'rel-1', description: 'Version number updated in package.json', required: true }, { id: 'rel-2', description: 'Changelog updated with all changes', required: true }, { id: 'rel-3', description: 'All tests pass', required: true }, { id: 'rel-4', description: 'TypeScript type checking passes', required: true }, { id: 'rel-5', description: 'Production build succeeds', required: true }, { id: 'rel-6', description: 'Database migrations applied', required: true }, { id: 'rel-7', description: 'Security review completed', required: true }, { id: 'rel-8', description: 'Performance benchmarks met', required: false }, { id: 'rel-9', description: 'Documentation updated', required: false }, { id: 'rel-10', description: 'Rollback plan documented', required: true } ]; }
  generateReleaseNotes(version: string): string { const changelog = this.getChangelog(); const entry = changelog.find((c) => c.version === version); if (!entry) return `No release notes found for version ${version}`; const lines = [`# Release ${entry.version} (${entry.date})`, '']; const grouped: Record<string, string[]> = {}; for (const change of entry.changes) { if (!grouped[change.type]) grouped[change.type] = []; grouped[change.type]!.push(change.description); } const labels: Record<string, string> = { added: 'Added', changed: 'Changed', fixed: 'Fixed', removed: 'Removed' }; for (const [type, items] of Object.entries(grouped)) { lines.push(`## ${labels[type] ?? type}`, ''); for (const item of items) lines.push(`- ${item}`); lines.push(''); } return lines.join('\n'); }
}

export const releaseService = new ReleaseService();
