import { memo, useState, useCallback } from 'react';
import { TrendingUp, Users, Mail, UserPlus } from 'lucide-react';
import { useMarketing } from '@/hooks/useMarketing';

function AnalyticsCardComponent() {
  const { loading, error, success, subscribeNewsletter, reset } = useMarketing();
  const [email, setEmail] = useState('');
  const handleSubmit = useCallback(async (e: React.FormEvent) => { e.preventDefault(); if (!email) return; const ok = await subscribeNewsletter(email, 'analytics_card'); if (ok) { setEmail(''); setTimeout(reset, 3000); } }, [email, subscribeNewsletter, reset]);
  return (<div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-50"><TrendingUp className="h-4 w-4 text-primary-600" /></div><h3 className="text-sm font-semibold text-neutral-900">SEO & Marketing Analytics</h3></div><div className="mb-4 grid grid-cols-3 gap-3"><div className="rounded-lg bg-neutral-50 p-3 text-center"><Users className="mx-auto mb-1 h-4 w-4 text-neutral-400" /><p className="text-lg font-bold text-neutral-900">--</p><p className="text-xs text-neutral-500">Leads</p></div><div className="rounded-lg bg-neutral-50 p-3 text-center"><Mail className="mx-auto mb-1 h-4 w-4 text-neutral-400" /><p className="text-lg font-bold text-neutral-900">--</p><p className="text-xs text-neutral-500">Subscribers</p></div><div className="rounded-lg bg-neutral-50 p-3 text-center"><TrendingUp className="mx-auto mb-1 h-4 w-4 text-neutral-400" /><p className="text-lg font-bold text-neutral-900">--</p><p className="text-xs text-neutral-500">Conversions</p></div></div><form onSubmit={handleSubmit} className="flex gap-2"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Enter email for newsletter" className="flex-1 rounded-lg border border-neutral-300 px-3 py-2 text-sm focus:border-primary-500 focus:outline-none" aria-label="Email for newsletter" /><button type="submit" disabled={loading} className="flex items-center gap-1.5 rounded-lg bg-primary-600 px-4 py-2 text-sm font-medium text-white hover:bg-primary-700 disabled:opacity-50"><UserPlus className="h-4 w-4" /> {loading ? '...' : 'Subscribe'}</button></form>{error && <p className="mt-2 text-xs text-error-600">{error}</p>}{success && <p className="mt-2 text-xs text-success-600">Successfully subscribed!</p>}</div>);
}
export const AnalyticsCard = memo(AnalyticsCardComponent);
