import { memo } from 'react';
import { Bell, AlertCircle, CheckCircle, Clock } from 'lucide-react';
import { alertService } from '@/services/monitoring';
import { getAlertSeverityColor } from '@/services/monitoring';

function AlertsPanelComponent() {
  const alerts = alertService.getAlerts('active', undefined, 20);
  const stats = alertService.getAlertStats();
  return (<div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-50"><Bell className="h-4 w-4 text-primary-600" /></div><h3 className="text-sm font-semibold text-neutral-900">Alerts</h3><span className="ml-auto rounded-full bg-error-50 px-2 py-0.5 text-xs font-medium text-error-700">{stats.active} active</span></div><div className="mb-3 grid grid-cols-4 gap-2 text-xs"><div className="rounded-lg bg-error-50 p-2.5 text-center"><p className="text-lg font-bold text-error-700">{stats.critical}</p><p className="text-error-400">Critical</p></div><div className="rounded-lg bg-error-50 p-2.5 text-center"><p className="text-lg font-bold text-error-700">{stats.high}</p><p className="text-error-400">High</p></div><div className="rounded-lg bg-warning-50 p-2.5 text-center"><p className="text-lg font-bold text-warning-700">{stats.medium}</p><p className="text-warning-400">Medium</p></div><div className="rounded-lg bg-neutral-50 p-2.5 text-center"><p className="text-lg font-bold text-neutral-900">{stats.low}</p><p className="text-neutral-400">Low</p></div></div><div className="space-y-2">{alerts.map((alert) => (<div key={alert.id} className="flex items-start gap-2 rounded-lg border border-neutral-100 p-2.5"><AlertCircle className="mt-0.5 h-4 w-4 flex-shrink-0 text-error-500" /><div className="flex-1"><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${getAlertSeverityColor(alert.severity)}`}>{alert.severity}</span><span className="text-xs font-medium text-neutral-700">{alert.title}</span></div><p className="mt-0.5 text-xs text-neutral-500">{alert.description}</p><div className="mt-1 flex items-center gap-2"><span className="text-xs text-neutral-400">{alert.module}</span><span className="flex items-center gap-0.5 text-xs text-neutral-400"><Clock className="h-3 w-3" /> {new Date(alert.createdAt).toLocaleString()}</span></div></div><div className="flex gap-1"><button onClick={() => alertService.acknowledgeAlert(alert.id)} className="rounded p-1 text-warning-500 hover:bg-warning-50" aria-label="Acknowledge"><Clock className="h-3.5 w-3.5" /></button><button onClick={() => alertService.resolveAlert(alert.id)} className="rounded p-1 text-success-500 hover:bg-success-50" aria-label="Resolve"><CheckCircle className="h-3.5 w-3.5" /></button></div></div>))}{alerts.length === 0 && <p className="text-sm text-neutral-400">No active alerts.</p>}</div></div>);
}
export const AlertsPanel = memo(AlertsPanelComponent);
