import { memo } from 'react';
import { FileCheck, CheckCircle, XCircle } from 'lucide-react';
import { auditMonitoringService } from '@/services/monitoring';

function AuditLogCardComponent() {
  const events = auditMonitoringService.getEvents(undefined, undefined, 20);
  const stats = auditMonitoringService.getAuditStats();
  return (<div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-50"><FileCheck className="h-4 w-4 text-primary-600" /></div><h3 className="text-sm font-semibold text-neutral-900">Audit Log</h3><span className="ml-auto rounded-full bg-neutral-50 px-2 py-0.5 text-xs font-medium text-neutral-600">{stats.total} events</span></div><div className="mb-3 grid grid-cols-3 gap-2 text-xs"><div className="rounded-lg bg-success-50 p-2.5 text-center"><p className="text-lg font-bold text-success-700">{stats.successful}</p><p className="text-success-400">Success</p></div><div className="rounded-lg bg-error-50 p-2.5 text-center"><p className="text-lg font-bold text-error-700">{stats.failed}</p><p className="text-error-400">Failed</p></div><div className="rounded-lg bg-warning-50 p-2.5 text-center"><p className="text-lg font-bold text-warning-700">{stats.securityEvents}</p><p className="text-warning-400">Security</p></div></div><div className="max-h-60 space-y-1.5 overflow-auto">{events.map((event) => (<div key={event.id} className="flex items-start gap-2 rounded-lg border border-neutral-100 p-2 text-xs">{event.outcome === 'success' ? <CheckCircle className="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-success-500" /> : <XCircle className="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-error-500" />}<div className="flex-1"><div className="flex items-center gap-2"><span className="font-medium text-neutral-700">{event.action}</span><span className="text-neutral-400">{event.module}</span><span className="ml-auto text-neutral-400">{new Date(event.timestamp).toLocaleString()}</span></div>{event.details && <p className="mt-0.5 text-neutral-500">{event.details}</p>}</div></div>))}{events.length === 0 && <p className="text-sm text-neutral-400">No audit events recorded.</p>}</div></div>);
}
export const AuditLogCard = memo(AuditLogCardComponent);
