import { memo } from 'react';
import { Bug, AlertCircle, CheckCircle } from 'lucide-react';
import { useErrorTracking } from '@/hooks/useErrorTracking';

function ErrorTrackingCardComponent() {
  const { errors, stats, resolveError } = useErrorTracking();
  return (<div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-50"><Bug className="h-4 w-4 text-primary-600" /></div><h3 className="text-sm font-semibold text-neutral-900">Error Tracking</h3><span className="ml-auto rounded-full bg-error-50 px-2 py-0.5 text-xs font-medium text-error-700">{stats.unresolved} unresolved</span></div><div className="mb-4 grid grid-cols-4 gap-2 text-xs"><div className="rounded-lg bg-neutral-50 p-2.5 text-center"><p className="text-lg font-bold text-neutral-900">{stats.total}</p><p className="text-neutral-400">Total</p></div><div className="rounded-lg bg-error-50 p-2.5 text-center"><p className="text-lg font-bold text-error-700">{stats.critical}</p><p className="text-error-400">Critical</p></div><div className="rounded-lg bg-warning-50 p-2.5 text-center"><p className="text-lg font-bold text-warning-700">{stats.high}</p><p className="text-warning-400">High</p></div><div className="rounded-lg bg-neutral-50 p-2.5 text-center"><p className="text-lg font-bold text-neutral-900">{stats.medium}</p><p className="text-neutral-400">Medium</p></div></div><div className="space-y-2">{errors.slice(0, 10).map((error) => (<div key={error.id} className="flex items-start gap-2 rounded-lg border border-neutral-100 p-2.5"><AlertCircle className="mt-0.5 h-4 w-4 flex-shrink-0 text-error-500" /><div className="flex-1"><p className="text-xs font-medium text-neutral-700">{error.name}</p><p className="text-xs text-neutral-500">{error.message}</p><div className="mt-1 flex items-center gap-2"><span className="text-xs text-neutral-400">{error.module}</span><span className="text-xs text-neutral-400">x{error.count}</span></div></div><button onClick={() => resolveError(error.id)} className="flex-shrink-0 rounded p-1 text-success-500 hover:bg-success-50" aria-label="Resolve error"><CheckCircle className="h-4 w-4" /></button></div>))}{errors.length === 0 && <p className="text-sm text-neutral-400">No unresolved errors.</p>}</div></div>);
}
export const ErrorTrackingCard = memo(ErrorTrackingCardComponent);
