import { memo } from 'react';
import { Clock, CheckCircle, AlertTriangle, XCircle } from 'lucide-react';
import { uptimeMonitoringService } from '@/services/monitoring';

function UptimeCardComponent() {
  const components = uptimeMonitoringService.getMonitoredComponents();
  const summary = uptimeMonitoringService.getUptimeSummary();
  return (<div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-50"><Clock className="h-4 w-4 text-primary-600" /></div><h3 className="text-sm font-semibold text-neutral-900">Uptime Monitoring</h3><span className="ml-auto rounded-full bg-success-50 px-2 py-0.5 text-xs font-medium text-success-700">{summary.overallUptime}%</span></div><div className="mb-3 grid grid-cols-3 gap-2 text-xs"><div className="rounded-lg bg-success-50 p-2.5 text-center"><p className="text-lg font-bold text-success-700">{summary.healthyComponents}</p><p className="text-success-400">Healthy</p></div><div className="rounded-lg bg-warning-50 p-2.5 text-center"><p className="text-lg font-bold text-warning-700">{summary.degradedComponents}</p><p className="text-warning-400">Degraded</p></div><div className="rounded-lg bg-error-50 p-2.5 text-center"><p className="text-lg font-bold text-error-700">{summary.unhealthyComponents}</p><p className="text-error-400">Down</p></div></div><div className="space-y-1.5">{components.map((comp) => (<div key={comp.component} className="flex items-center justify-between text-xs"><div className="flex items-center gap-2">{comp.status === 'healthy' ? <CheckCircle className="h-3.5 w-3.5 text-success-500" /> : comp.status === 'degraded' ? <AlertTriangle className="h-3.5 w-3.5 text-warning-500" /> : <XCircle className="h-3.5 w-3.5 text-error-500" />}<span className="text-neutral-600">{comp.component}</span></div><div className="flex items-center gap-2"><span className="font-mono text-neutral-400">{comp.uptime}%</span><span className="text-neutral-400">{Math.round(comp.lastResponseTime)}ms</span></div></div>))}</div></div>);
}
export const UptimeCard = memo(UptimeCardComponent);
