export { HomePage } from '@/pages/HomePage';
export { UnauthorizedPage } from '@/pages/UnauthorizedPage';
export { AccessDeniedPage } from '@/pages/AccessDeniedPage';
export { ForbiddenPage } from '@/pages/ForbiddenPage';
export { NotFoundPage } from '@/pages/NotFoundPage';
export { ProfilePage } from '@/pages/ProfilePage';
export { DashboardPage } from '@/pages/admin/DashboardPage';
export { StudentDashboardPage } from '@/pages/student/DashboardPage';
export { BatchListPage } from '@/pages/student/BatchListPage';
export { BatchDetailsPage } from '@/pages/student/BatchDetailsPage';
export { SubjectPage } from '@/pages/student/SubjectPage';
export { ChapterPage } from '@/pages/student/ChapterPage';
export { ClassPage } from '@/pages/student/ClassPage';
export { McqDashboardPage } from '@/pages/student/McqDashboardPage';
export { McqPlayerPage } from '@/pages/student/McqPlayerPage';
export { McqResultPage } from '@/pages/student/McqResultPage';
export { McqReviewPage } from '@/pages/student/McqReviewPage';
export { LoginPage, RegisterPage, ForgotPasswordPage, ResetPasswordPage } from '@/pages/auth';
