import { memo } from 'react';
import { Package, GitBranch } from 'lucide-react';
import { buildOptimizationService } from '@/services/devops';

function BuildInformationCardComponent() {
  const buildInfo = buildOptimizationService.getBuildInfo();
  const optimizations = buildOptimizationService.getOptimizationStatus();
  const bundleAnalysis = buildOptimizationService.getBundleAnalysis();
  return (<div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-50"><Package className="h-4 w-4 text-primary-600" /></div><h3 className="text-sm font-semibold text-neutral-900">Build Information</h3></div><div className="mb-4 grid grid-cols-2 gap-3 text-xs"><div className="rounded-lg bg-neutral-50 p-2.5"><p className="text-neutral-400">Version</p><p className="font-mono font-medium text-neutral-700">{buildInfo.version}</p></div><div className="rounded-lg bg-neutral-50 p-2.5"><p className="text-neutral-400">Build Number</p><p className="font-mono font-medium text-neutral-700">{buildInfo.buildNumber}</p></div><div className="rounded-lg bg-neutral-50 p-2.5"><p className="text-neutral-400">Git Hash</p><p className="flex items-center gap-1 font-mono font-medium text-neutral-700"><GitBranch className="h-3 w-3" /> {buildInfo.gitHash.slice(0, 7)}</p></div><div className="rounded-lg bg-neutral-50 p-2.5"><p className="text-neutral-400">Target</p><p className="font-mono font-medium text-neutral-700">{buildInfo.target}</p></div></div><div className="mb-4"><h4 className="mb-2 text-xs font-semibold text-neutral-500">Optimization Status</h4><div className="space-y-1.5">{optimizations.map((opt) => (<div key={opt.feature} className="flex items-center justify-between text-xs"><span className="text-neutral-600">{opt.feature}</span><span className={`rounded-full px-2 py-0.5 font-medium ${opt.enabled ? 'bg-success-50 text-success-700' : 'bg-neutral-50 text-neutral-500'}`}>{opt.enabled ? 'Enabled' : 'Disabled'}</span></div>))}</div></div><div><h4 className="mb-2 text-xs font-semibold text-neutral-500">Bundle Analysis</h4><div className="space-y-1.5">{bundleAnalysis.map((chunk) => (<div key={chunk.chunk} className="flex items-center justify-between text-xs"><span className="text-neutral-600">{chunk.chunk}</span><span className="font-mono text-neutral-400">{chunk.estimatedSize}</span></div>))}</div></div></div>);
}
export const BuildInformationCard = memo(BuildInformationCardComponent);
