import { memo, useState, useEffect } from 'react';
import { Database, CheckCircle, XCircle, Loader } from 'lucide-react';
import { databaseOptimizationService } from '@/services/devops';
import type { DatabaseHealth } from '@/services/devops';

function DatabaseHealthCardComponent() {
  const [health, setHealth] = useState<DatabaseHealth | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void databaseOptimizationService.getDatabaseHealth().then((h) => { setHealth(h); setLoading(false); }); }, []);
  const suggestions = databaseOptimizationService.getOptimizationSuggestions();
  const maintenance = databaseOptimizationService.getMaintenanceTasks();
  const poolConfig = databaseOptimizationService.getConnectionPoolConfig();
  return (<div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-50"><Database className="h-4 w-4 text-primary-600" /></div><h3 className="text-sm font-semibold text-neutral-900">Database Health</h3></div>{loading ? <div className="flex items-center gap-2 text-sm text-neutral-400"><Loader className="h-4 w-4 animate-spin" /> Checking database...</div> : health && (<><div className="mb-4 flex items-center gap-2 rounded-lg bg-neutral-50 p-3">{health.healthy ? <CheckCircle className="h-5 w-5 text-success-500" /> : <XCircle className="h-5 w-5 text-error-500" />}<span className="text-sm font-medium text-neutral-700">{health.message}</span></div><div className="mb-4 grid grid-cols-3 gap-3 text-xs"><div className="rounded-lg bg-neutral-50 p-2.5 text-center"><p className="text-lg font-bold text-neutral-900">{health.totalTables}</p><p className="text-neutral-400">Tables</p></div><div className="rounded-lg bg-neutral-50 p-2.5 text-center"><p className="text-lg font-bold text-neutral-900">{health.totalIndexes}</p><p className="text-neutral-400">Indexes</p></div><div className="rounded-lg bg-neutral-50 p-2.5 text-center"><p className="text-lg font-bold text-neutral-900">{health.totalPolicies}</p><p className="text-neutral-400">RLS Policies</p></div></div><div className="mb-4"><h4 className="mb-2 text-xs font-semibold text-neutral-500">Optimization Suggestions</h4><div className="space-y-1.5">{suggestions.map((s) => (<div key={s.id} className="rounded-lg border border-neutral-100 p-2"><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${s.severity === 'critical' ? 'bg-error-50 text-error-700' : s.severity === 'high' ? 'bg-warning-50 text-warning-700' : 'bg-neutral-50 text-neutral-600'}`}>{s.severity}</span><span className="text-xs text-neutral-600">{s.description}</span></div><p className="mt-1 text-xs text-neutral-400">{s.recommendation}</p></div>))}</div></div><div className="mb-4"><h4 className="mb-2 text-xs font-semibold text-neutral-500">Maintenance Tasks</h4><div className="space-y-1">{maintenance.map((m) => <div key={m.id} className="flex items-center justify-between text-xs text-neutral-500"><span>{m.task}</span><span className="text-neutral-400">{m.frequency} | {m.lastRun}</span></div>)}</div></div><div className="rounded-lg bg-neutral-50 p-3"><h4 className="mb-1 text-xs font-semibold text-neutral-500">Connection Pool</h4><div className="grid grid-cols-3 gap-2 text-xs"><div><span className="text-neutral-400">Min:</span> {poolConfig.minConnections}</div><div><span className="text-neutral-400">Max:</span> {poolConfig.maxConnections}</div><div><span className="text-neutral-400">Idle:</span> {poolConfig.idleTimeoutMs}ms</div></div><p className="mt-1 text-xs text-neutral-400">{poolConfig.recommendation}</p></div></>)}</div>);
}
export const DatabaseHealthCard = memo(DatabaseHealthCardComponent);
