import { memo } from 'react';
import { Rocket, CheckCircle, Clock, XCircle } from 'lucide-react';
import { useDeployment } from '@/hooks/useDeployment';

function DeploymentStatusCardComponent() {
  const { deployments, latest, checklist } = useDeployment();
  const statusIcon = (status: string) => { switch (status) { case 'success': return <CheckCircle className="h-4 w-4 text-success-500" />; case 'failed': case 'rolled_back': return <XCircle className="h-4 w-4 text-error-500" />; case 'building': case 'deploying': case 'pending': return <Clock className="h-4 w-4 text-warning-500" />; default: return <Clock className="h-4 w-4 text-neutral-400" />; } };
  return (<div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-50"><Rocket className="h-4 w-4 text-primary-600" /></div><h3 className="text-sm font-semibold text-neutral-900">Deployment Status</h3></div>{latest ? (<div className="mb-4 rounded-lg bg-neutral-50 p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2">{statusIcon(latest.status)}<span className="text-sm font-medium text-neutral-700">v{latest.version}</span></div><span className="text-xs text-neutral-400">{new Date(latest.startedAt).toLocaleString()}</span></div><p className="mt-1 text-xs text-neutral-500">{latest.message}</p></div>) : <p className="mb-4 text-sm text-neutral-400">No deployments recorded yet.</p>}<div className="space-y-1.5"><h4 className="text-xs font-semibold text-neutral-500">Deployment Checklist</h4>{checklist.map((item) => (<div key={item.id} className="flex items-center gap-2 text-xs text-neutral-600"><span className="h-1.5 w-1.5 rounded-full bg-neutral-300" />{item.description}{item.required && <span className="text-neutral-400">*Required</span>}</div>))}</div>{deployments.length > 0 && (<div className="mt-4 space-y-1.5"><h4 className="text-xs font-semibold text-neutral-500">Recent Deployments</h4>{deployments.slice(0, 5).map((dep) => (<div key={dep.id} className="flex items-center justify-between text-xs text-neutral-500"><span className="flex items-center gap-1.5">{statusIcon(dep.status)} v{dep.version}</span><span>{new Date(dep.startedAt).toLocaleDateString()}</span></div>))}</div>)}</div>);
}
export const DeploymentStatusCard = memo(DeploymentStatusCardComponent);
