import { memo, useState, useEffect, useCallback } from 'react';
import { Activity, RefreshCw, CheckCircle, XCircle, AlertTriangle } from 'lucide-react';
import { useHealthChecks } from '@/hooks/useHealthChecks';

function HealthDashboardComponent() {
  const { checks, overallHealth, loading, runChecks } = useHealthChecks();
  const [autoRefresh, setAutoRefresh] = useState(false);
  useEffect(() => { void runChecks(); }, [runChecks]);
  const handleRefresh = useCallback(() => { void runChecks(); }, [runChecks]);
  useEffect(() => { if (!autoRefresh) return; const interval = setInterval(() => void runChecks(), 30000); return () => clearInterval(interval); }, [autoRefresh, runChecks]);
  const statusIcon = (status: string) => { switch (status) { case 'healthy': return <CheckCircle className="h-4 w-4 text-success-500" />; case 'degraded': return <AlertTriangle className="h-4 w-4 text-warning-500" />; case 'unhealthy': return <XCircle className="h-4 w-4 text-error-500" />; default: return <Activity className="h-4 w-4 text-neutral-400" />; } };
  return (<div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-50"><Activity className="h-4 w-4 text-primary-600" /></div><h3 className="text-sm font-semibold text-neutral-900">Health Dashboard</h3></div><div className="flex items-center gap-2"><label className="flex items-center gap-1 text-xs text-neutral-500"><input type="checkbox" checked={autoRefresh} onChange={(e) => setAutoRefresh(e.target.checked)} className="h-3 w-3" /> Auto-refresh</label><button onClick={handleRefresh} disabled={loading} className="flex items-center gap-1 rounded-lg border border-neutral-300 px-2 py-1 text-xs text-neutral-600 hover:bg-neutral-100 disabled:opacity-50"><RefreshCw className={`h-3 w-3 ${loading ? 'animate-spin' : ''}`} /> Refresh</button></div></div>{overallHealth && (<div className="mb-4 flex items-center gap-2 rounded-lg bg-neutral-50 p-3">{statusIcon(overallHealth.status)}<span className="text-sm font-medium text-neutral-700">{overallHealth.message}</span><span className={`ml-auto rounded-full px-2 py-0.5 text-xs font-medium ${overallHealth.healthy ? 'bg-success-50 text-success-700' : 'bg-error-50 text-error-700'}`}>{overallHealth.status.toUpperCase()}</span></div>)}<div className="space-y-2">{checks.map((check) => (<div key={check.component} className="flex items-center justify-between rounded-lg border border-neutral-100 p-2.5"><div className="flex items-center gap-2">{statusIcon(check.status)}<span className="text-sm font-medium capitalize text-neutral-700">{check.component}</span></div><div className="flex items-center gap-3"><span className="text-xs text-neutral-400">{check.responseTime > 0 ? `${Math.round(check.responseTime)}ms` : '--'}</span><span className="text-xs text-neutral-500">{check.message}</span></div></div>))}{checks.length === 0 && !loading && <p className="text-sm text-neutral-400">No health checks run yet.</p>}</div></div>);
}
export const HealthDashboard = memo(HealthDashboardComponent);
