import { memo } from 'react';
import { useParams } from 'react-router-dom';
import { CheckCircle, Users, BookOpen, Award, TrendingUp } from 'lucide-react';
import { MetaManager, StructuredData, BreadcrumbSEO } from '@/components/seo';
import { LeadCaptureForm, NewsletterForm } from '@/components/seo';
import { seoService } from '@/services/seo';

const LANDING_DATA: Record<string, { name: string; title: string; subtitle: string; description: string; keywords: string[]; features: string[]; faqs: { question: string; answer: string }[] }> = {
  norcet: { name: 'NORCET', title: 'NORCET Coaching - Best Online Preparation', subtitle: 'Master the Nursing Officer Recruitment Common Eligibility Test', description: 'Comprehensive NORCET exam preparation with expert-led video courses, mock tests, and study materials. Join thousands of successful candidates.', keywords: ['NORCET', 'NORCET coaching', 'NORCET preparation', 'NORCET online course', 'nursing officer exam'], features: ['500+ Video Lectures', '1000+ Practice Questions', 'Full-length Mock Tests', 'Expert Faculty', 'Detailed Performance Analytics', '24/7 Doubt Resolution'], faqs: [{ question: 'What is NORCET?', answer: 'NORCET (Nursing Officer Recruitment Common Eligibility Test) is a national-level examination conducted by AIIMS for recruiting nursing officers across India.' }, { question: 'How can I prepare for NORCET?', answer: 'Our comprehensive online course includes video lectures, practice questions, mock tests, and performance analytics to help you crack NORCET.' }, { question: 'What is the eligibility for NORCET?', answer: 'Candidates must have B.Sc. Nursing or GNM diploma and be registered with the State Nursing Council.' }, { question: 'How much does NORCET coaching cost?', answer: 'We offer flexible pricing plans starting from affordable rates. Check our batch pricing for detailed information.' }] },
  'nursing-officer': { name: 'Nursing Officer', title: 'Nursing Officer Exam Coaching - Online Preparation', subtitle: 'Your pathway to a government nursing career', description: 'Prepare for Nursing Officer recruitment exams with comprehensive online courses covering all subjects, mock tests, and expert guidance.', keywords: ['nursing officer', 'nursing officer exam', 'nursing officer coaching', 'staff nurse exam'], features: ['Complete Subject Coverage', 'Previous Year Papers', 'Weekly Test Series', 'Expert Mentorship', 'Performance Tracking', 'Mobile-friendly Learning'], faqs: [{ question: 'What is a Nursing Officer exam?', answer: 'Nursing Officer exams are conducted by various government institutions to recruit staff nurses for hospitals and healthcare facilities.' }, { question: 'How do I start preparing?', answer: 'Enroll in our comprehensive course, start with video lectures, practice with mock tests, and track your progress with our analytics dashboard.' }] },
  aiims: { name: 'AIIMS', title: 'AIIMS Nursing Exam Coaching - Best Online Preparation', subtitle: 'Crack the AIIMS nursing entrance exam', description: 'Expert-led AIIMS nursing exam preparation with video lectures, practice tests, and study materials designed by experienced faculty.', keywords: ['AIIMS nursing', 'AIIMS nursing exam', 'AIIMS coaching', 'AIIMS preparation'], features: ['AIIMS-specific Content', 'Subject-wise Tests', 'Expert Video Lectures', 'Performance Analytics', 'Doubt Clearing Sessions', 'Study Planner'], faqs: [{ question: 'What is AIIMS nursing exam?', answer: 'AIIMS conducts nursing officer recruitment exams for its various institutions across India.' }, { question: 'How is this course different?', answer: 'Our AIIMS course is specifically designed around the AIIMS exam pattern with focused content and practice tests.' }] },
  esic: { name: 'ESIC', title: 'ESIC Nursing Exam Coaching - Online Preparation', subtitle: 'Excel in ESIC nursing officer recruitment', description: 'Complete ESIC nursing exam preparation with comprehensive study materials, video lectures, and mock tests.', keywords: ['ESIC nursing', 'ESIC exam', 'ESIC coaching', 'ESIC nursing officer'], features: ['ESIC Exam Pattern Coverage', 'Video Lectures', 'Mock Tests', 'Study Notes', 'Performance Tracking', 'Expert Guidance'], faqs: [{ question: 'What is ESIC nursing exam?', answer: 'ESIC (Employees State Insurance Corporation) conducts exams for recruiting nursing officers for its hospitals across India.' }] },
  dsssb: { name: 'DSSSB', title: 'DSSSB Nursing Exam Coaching - Online Preparation', subtitle: 'Your guide to DSSSB nursing officer success', description: 'Prepare for DSSSB nursing exams with our comprehensive online course featuring video lectures, practice tests, and expert guidance.', keywords: ['DSSSB nursing', 'DSSSB exam', 'DSSSB coaching', 'DSSSB nursing officer'], features: ['DSSSB Pattern Coverage', 'Subject-wise Video Lectures', 'Practice Tests', 'Previous Year Papers', 'Performance Analytics', 'Expert Faculty'], faqs: [{ question: 'What is DSSSB nursing exam?', answer: 'DSSSB (Delhi Subordinate Services Selection Board) conducts exams for recruiting nursing officers for Delhi government hospitals.' }] },
  cho: { name: 'CHO', title: 'CHO Exam Coaching - Community Health Officer Preparation', subtitle: 'Become a certified Community Health Officer', description: 'Complete CHO exam preparation with specialized courses covering community health, public health, and clinical subjects.', keywords: ['CHO', 'CHO exam', 'community health officer', 'CHO coaching', 'CHO preparation'], features: ['Community Health Focus', 'Clinical Subject Coverage', 'Mock Tests', 'Case Studies', 'Expert Mentorship', 'Performance Analytics'], faqs: [{ question: 'What is CHO exam?', answer: 'CHO (Community Health Officer) exam is conducted for recruiting community health officers to work at Health and Wellness Centres under Ayushman Bharat.' }] },
  'rrb-nursing-officer': { name: 'RRB Nursing Officer', title: 'RRB Nursing Officer Exam Coaching - Online Preparation', subtitle: 'Crack the Railway Recruitment Board nursing exam', description: 'Complete RRB Nursing Officer exam preparation with video lectures, mock tests, and study materials designed for railway nursing recruitment.', keywords: ['RRB nursing officer', 'RRB exam', 'railway nursing', 'RRB coaching'], features: ['RRB Exam Pattern', 'Video Lectures', 'Mock Tests', 'Study Materials', 'Performance Tracking', 'Expert Guidance'], faqs: [{ question: 'What is RRB Nursing Officer exam?', answer: 'RRB (Railway Recruitment Board) conducts exams for recruiting nursing officers for railway hospitals across India.' }] },
};

function LandingPageComponent() {
  const { slug } = useParams<{ slug: string }>();
  const data = slug ? LANDING_DATA[slug] : undefined;
  if (!data) { return <div className="flex h-40 items-center justify-center text-neutral-400">Landing page not found.</div>; }
  const meta = seoService.generateLandingPageMeta(data.name, data.description);
  return (<><MetaManager title={meta.title ?? data.title} description={meta.description ?? data.description} keywords={data.keywords.join(', ')} canonicalPath={`/landing/${slug}`} /><StructuredData type="faq" data={{ faqs: data.faqs }} /><StructuredData type="organization" /><BreadcrumbSEO items={[{ name: 'Home', path: '/' }, { name: data.name, path: `/landing/${slug}` }]} /><div className="min-h-screen bg-gradient-to-b from-primary-50 to-white"><div className="mx-auto max-w-4xl px-4 py-12"><div className="mb-8 text-center"><h1 className="mb-3 text-4xl font-bold text-neutral-900">{data.title}</h1><p className="text-lg text-neutral-600">{data.subtitle}</p></div><p className="mb-8 text-center text-neutral-700">{data.description}</p><div className="mb-12 grid grid-cols-2 gap-4 sm:grid-cols-3">{data.features.map((feature) => (<div key={feature} className="flex items-center gap-2 rounded-xl bg-white p-3 shadow-sm"><CheckCircle className="h-5 w-5 flex-shrink-0 text-success-500" /><span className="text-sm text-neutral-700">{feature}</span></div>))}</div><div className="mb-12 grid grid-cols-1 gap-4 sm:grid-cols-4"><div className="rounded-xl bg-white p-4 text-center shadow-sm"><Users className="mx-auto mb-1 h-6 w-6 text-primary-500" /><p className="text-2xl font-bold text-neutral-900">10K+</p><p className="text-xs text-neutral-500">Students</p></div><div className="rounded-xl bg-white p-4 text-center shadow-sm"><BookOpen className="mx-auto mb-1 h-6 w-6 text-primary-500" /><p className="text-2xl font-bold text-neutral-900">500+</p><p className="text-xs text-neutral-500">Lessons</p></div><div className="rounded-xl bg-white p-4 text-center shadow-sm"><Award className="mx-auto mb-1 h-6 w-6 text-primary-500" /><p className="text-2xl font-bold text-neutral-900">95%</p><p className="text-xs text-neutral-500">Pass Rate</p></div><div className="rounded-xl bg-white p-4 text-center shadow-sm"><TrendingUp className="mx-auto mb-1 h-6 w-6 text-primary-500" /><p className="text-2xl font-bold text-neutral-900">4.8</p><p className="text-xs text-neutral-500">Rating</p></div></div><div className="mb-12"><h2 className="mb-4 text-2xl font-bold text-neutral-900">Frequently Asked Questions</h2><div className="space-y-3">{data.faqs.map((faq) => (<div key={faq.question} className="rounded-xl bg-white p-4 shadow-sm"><h3 className="mb-1 text-sm font-semibold text-neutral-900">{faq.question}</h3><p className="text-sm text-neutral-600">{faq.answer}</p></div>))}</div></div><div className="grid grid-cols-1 gap-4 lg:grid-cols-2"><LeadCaptureForm examTarget={data.name} landingPage={`/landing/${slug}`} title="Get Free Counseling" /><div className="rounded-xl border border-neutral-200 bg-white p-5 shadow-sm"><h3 className="mb-4 text-sm font-semibold text-neutral-900">Subscribe to Our Newsletter</h3><NewsletterForm source={`landing_${slug}`} /></div></div></div></div></>);
}
export const LandingPage = memo(LandingPageComponent);
