import type { HealthCheck, HealthStatus } from './monitoring.types';
import { loggingService } from './loggingService';

class HealthMonitoringService {
  async checkDatabase(): Promise<HealthCheck> {
    const start = performance.now();
    try { const { getSupabaseClient } = await import('@/lib/supabase'); const supabase = getSupabaseClient(); const { error } = await supabase.from('profiles').select('id').limit(1).maybeSingle(); const responseTime = performance.now() - start; const status: HealthStatus = error ? 'unhealthy' : 'healthy'; return { id: `hc-db-${Date.now()}`, component: 'Database', status, message: error ? error.message : 'Database connection healthy', responseTime, timestamp: new Date().toISOString(), lastChecked: new Date().toISOString() }; } catch (err) { return { id: `hc-db-${Date.now()}`, component: 'Database', status: 'unhealthy', message: err instanceof Error ? err.message : 'Unknown error', responseTime: performance.now() - start, timestamp: new Date().toISOString(), lastChecked: new Date().toISOString() }; }
  }
  async checkAPI(): Promise<HealthCheck> {
    const start = performance.now();
    try { const { getSupabaseClient } = await import('@/lib/supabase'); const supabase = getSupabaseClient(); const { error } = await supabase.auth.getSession(); const responseTime = performance.now() - start; return { id: `hc-api-${Date.now()}`, component: 'API', status: !error ? 'healthy' : 'degraded', message: !error ? 'API reachable' : error.message, responseTime, timestamp: new Date().toISOString(), lastChecked: new Date().toISOString() }; } catch (err) { return { id: `hc-api-${Date.now()}`, component: 'API', status: 'unhealthy', message: err instanceof Error ? err.message : 'Unknown error', responseTime: performance.now() - start, timestamp: new Date().toISOString(), lastChecked: new Date().toISOString() }; }
  }
  async checkStorage(): Promise<HealthCheck> {
    const start = performance.now();
    try { const { getSupabaseClient } = await import('@/lib/supabase'); const supabase = getSupabaseClient(); const { data, error } = await supabase.storage.listBuckets(); const responseTime = performance.now() - start; return { id: `hc-storage-${Date.now()}`, component: 'Storage', status: error ? 'unhealthy' : 'healthy', message: error ? error.message : `${data?.length ?? 0} buckets available`, responseTime, timestamp: new Date().toISOString(), lastChecked: new Date().toISOString() }; } catch (err) { return { id: `hc-storage-${Date.now()}`, component: 'Storage', status: 'unhealthy', message: err instanceof Error ? err.message : 'Unknown error', responseTime: performance.now() - start, timestamp: new Date().toISOString(), lastChecked: new Date().toISOString() }; }
  }
  async checkAuthentication(): Promise<HealthCheck> {
    const start = performance.now();
    try { const { getSupabaseClient } = await import('@/lib/supabase'); const supabase = getSupabaseClient(); const { data, error } = await supabase.auth.getSession(); const responseTime = performance.now() - start; return { id: `hc-auth-${Date.now()}`, component: 'Authentication', status: !error ? 'healthy' : 'degraded', message: !error ? (data.session ? 'Session active' : 'No session (OK)') : error.message, responseTime, timestamp: new Date().toISOString(), lastChecked: new Date().toISOString() }; } catch (err) { return { id: `hc-auth-${Date.now()}`, component: 'Authentication', status: 'unhealthy', message: err instanceof Error ? err.message : 'Unknown error', responseTime: performance.now() - start, timestamp: new Date().toISOString(), lastChecked: new Date().toISOString() }; }
  }
  checkEnvironment(): HealthCheck { const url = import.meta.env.VITE_SUPABASE_URL; const key = import.meta.env.VITE_SUPABASE_ANON_KEY; const ok = !!url && !!key; return { id: `hc-env-${Date.now()}`, component: 'Environment', status: ok ? 'healthy' : 'unhealthy', message: ok ? 'All env vars configured' : 'Missing env vars', responseTime: 0, timestamp: new Date().toISOString(), lastChecked: new Date().toISOString() }; }
  async runAllHealthChecks(): Promise<HealthCheck[]> { const [db, api, storage, auth] = await Promise.all([this.checkDatabase(), this.checkAPI(), this.checkStorage(), this.checkAuthentication()]); const env = this.checkEnvironment(); const checks = [env, db, api, storage, auth]; for (const check of checks) { if (check.status !== 'healthy') loggingService.warning('Health', `${check.component}: ${check.message}`); } return checks; }
  getOverallHealth(checks: HealthCheck[]): { score: number; status: HealthStatus } { const healthy = checks.filter((c) => c.status === 'healthy').length; const score = Math.round((healthy / checks.length) * 100); const status: HealthStatus = score === 100 ? 'healthy' : score >= 60 ? 'degraded' : 'unhealthy'; return { score, status }; }
  getMonitoredComponents(): { name: string; category: string; critical: boolean }[] { return [ { name: 'API', category: 'Infrastructure', critical: true }, { name: 'Database', category: 'Infrastructure', critical: true }, { name: 'Supabase', category: 'Infrastructure', critical: true }, { name: 'Storage', category: 'Infrastructure', critical: true }, { name: 'Authentication', category: 'Security', critical: true }, { name: 'Payments', category: 'Business', critical: true }, { name: 'Streaming', category: 'Content', critical: false }, { name: 'Notifications', category: 'Communication', critical: false }, { name: 'AI Services', category: 'Intelligence', critical: false } ]; }
}

export const healthMonitoringService = new HealthMonitoringService();
